repo_name: 'tutorials'
repo_info: >
  <img style="float: right; width: 100px" src="https://raw.github.com/pyomeca/design/master/logo/logo_cropped_doc.svg?sanitize=true">

  <font size="+3">Effective computation in Biomechanics</font>


  <font size="+2">Romain Martinez</font> <a href="https://github.com/romainmartinez"><img src="https://img.shields.io/badge/github-romainmartinez-green?logo=github&style=social" /></a>